[package]
name = "flood_plugin"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.15", default-features = false, features = [
  "bevy_render",
  "bevy_core_pipeline",
  "bevy_winit",
  "bevy_sprite",
  "x11",
  "png",
] }

[[example]]
name = "sdf" 
path = "examples/sdf.rs"

[[example]]
name = "alpha_mask" 
path = "examples/alpha_mask.rs"
