[package]
name = "flood_plugin"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.15.1"

[[example]]
name = "sdf" 
path = "examples/sdf.rs"

[[example]]
name = "alpha_mask" 
path = "examples/alpha_mask.rs"
